<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>

    <Reference Include="GameProj">
      <HintPath>..\input\GameProj.dll</HintPath>
      <Private>true</Private>
    </Reference>

    <Reference Include="Assembly-CSharp">
      <HintPath>..\input\Assembly-CSharp.dll</HintPath>
      <Private>true</Private>
    </Reference>

    <Reference Include="FMBase">
      <HintPath>..\input\FMBase.dll</HintPath>
      <Private>true</Private>
    </Reference>

    <Reference Include="FMCommon">
      <HintPath>..\input\FMCommon.dll</HintPath>
      <Private>true</Private>
    </Reference>

    <None Include="..\input\UnityEngine*.dll">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>

    <None Include="..\input\Unity.TextMeshPro.dll">
      <Link>Unity.TextMeshPro.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>

    <None Include="..\input\Newtonsoft.Json.dll">
      <Link>Newtonsoft.Json.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>

    <None Include="..\input\Unity.SharpZipLib.dll">
      <Link>Unity.SharpZipLib.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>

  </ItemGroup>

</Project>